### ISSUE TITLE
Matching GTK and icon themes

### ISSUE THREAD

**Issue by omrisim210** [dylanaraps/pywal#27]
Could you implement matching GTK and icon themes like how [wpgtk](https://github.com/deviantfero/wpgtk) does it?

**Comment by dylanaraps** [comment]
Yes, I'll start working on it.

**Comment by omrisim210** [comment]
Great, can't wait to see it in action!

**Comment by dylanaraps** [comment]
GTK2 support has been added.

See the wiki for instructions: https://github.com/dylanaraps/pywal/wiki/Customization#system-themes

Note: You'll need to use the `git` version of `pywal`. I'll release a regular version with GTK2 support later this week. Right now I'm looking for feedback on whether or not it works for you guys.

**Comment by tkamat** [comment]
Seems to work well for me, gtk2 is working fine but requires application restart, and gtk3 is no longer broken. Some of the colors look a bit weird with certain wallpapers, but that is to be expected.

**Comment by dylanaraps** [comment]
Do you have `Python 2` installed? The on the fly theme reload requires Python 2. 

This is because the Python 3 GTK/Gdk libraries don't support `send_clientmessage_toall()` which is needed to tell all windows to refresh their themes. The only other solution is shipping a small `C` file with `pywal` which I'll look into.

(Sorry, I should've made it clearer. I've updated the Wiki)

**Comment by dylanaraps** [comment]
@tkamat, I just pushed an update to the theme that makes everything more readable. Update both `pywal` and the GTK theme and let me know if you've got anymore feedback.

Screenshot:

![2017-07-25-02-19-21](https://user-images.githubusercontent.com/6799467/28555607-5a860b20-7144-11e7-9d7e-fb1acf3e964b.png)

**Comment by omrisim210** [comment]
I'm on Cinnamon and it doesn't even show me the theme in the theme selection menu.  
Is that because it's a gtk2 theme and the Cinnamon theme switcher uses gtk3? Because I can set it in LXAppearance and `~/.gtkrc-2.0` and it even shows in the former (the program uses my `wal` colors) but it resets after I close LXAppearance.  
I know gtk3 uses css for theming so it shouldn't be *that* hard to theme it but I really don't know where to start

P.S. If there will be a gtk3 theme I think it should live in it's own repository and simply import (or whatever the CSS equivalent is) the css colors that `wal` already exports

**Comment by dylanaraps** [comment]
> I'm on Cinnamon and it doesn't even show me the theme in the theme selection menu.

Did you download and install `Flatabulous-wal` to `~/.themes`? Anyway, I'll push an update to make it show up in the switcher.

> P.S. If there will be a gtk3 theme I think it should live in it's own repository and simply import (or whatever the CSS equivalent is) the css colors that wal already exports

That's the plan and it's exactly what the GTK2 theme currently does.

**Comment by omrisim210** [comment]
> Did you download and install Flatabulous-wal to ~/.themes? Anyway, I'll push an update to make it show up in the switcher.

Yeah, I did.

> That's the plan and it's exactly what the GTK2 theme currently does.

Great!

**Comment by tkamat** [comment]
Thanks for the update! The on the fly switching is working properly, and the colors are much better, but I am still getting some unreadable text. Here is an example from gimp, as you can see some of the menu options at the top are only visible when you mouse over them. 
![2017-07-26-1501101701_screenshot_1920x1080](https://user-images.githubusercontent.com/22806585/28642708-f2d6c9b4-7270-11e7-8221-7a6c654bd993.jpg)

**Comment by dylanaraps** [comment]
Do you have `gtk-engine-murrine` installed? I took a peek in the Flatabulous source and I'm pretty sure it requires it for some styling.

**Comment by tkamat** [comment]
Never mind, I managed to fix it and it is now working wonderfully! Are you planning GTK3 support in the near future? I might be able to contribute if you are.

**Comment by dylanaraps** [comment]
Yep!

The first step is finding a suitable GTK3 theme to use as a base. I want to skip the GTK theme build process and instead modify the compiled theme directly. The build process does make things easier to edit but it also adds needless dependencies and the compilation takes too long.

Any suggestions for GTK3 themes?

**Comment by tkamat** [comment]
How about Paper? It seems like a popular, flat, and easy to modify gtk3 theme that fits well for what you are trying to accomplish. I have started tinkering with it and it seems promising, the css files are orderly and it has been pretty easy to import the exported colors from wal. I will let you know if I find a better alternative or if I get it working.

**Comment by dylanaraps** [comment]
Awesome, I'll take a look.

**Comment by HonorOfDuty** [comment]
The problem that i'm running into at the moment is that every time i change wallpaper with pywal, the background of the filemanager does not change. i.e. it remains the colour that was assigned when I started i3(see pictures). This changes upon restart of my filemanager.

I've treid this with both thunar and pcmanfm with the same result
![before](https://user-images.githubusercontent.com/29234554/28784634-3fa440fe-7614-11e7-8603-27241cc621ef.png)
![after](https://user-images.githubusercontent.com/29234554/28784635-3fb022ca-7614-11e7-9377-dc54924a492c.png)

**Comment by dylanaraps** [comment]
This is an issue with the file manager and not `pywal`, you'll notice it happens with `lxappearence` and other tools.

**Comment by dylanaraps** [comment]
We should be able to incorporate [wpgtk-themes](https://github.com/deviantfero/wpgtk-themes) as the theme of choice for `pywal`. These themes are already in use by `wpgtk` and incorporating them skips us reinventing the wheel to add theme support.

This will allow us to cover GTK2, GTK3 and Icons. I'm going to start messing around in a local branch to see if I can get this working. :)

**Comment by Jab2870** [comment]
Thanks for all your work on this.  If you like, I could open a new ticket but how much extra work would it be to have a qt/plasma theme as well?

**Comment by kotajacob** [comment]
@dylanaraps So I'm looking into making a colourable version or the [arc gtk theme](https://github.com/horst3180/Arc-theme). When you made the modification to Flatabulous did you do it in a way where it pywal will detect and color any "wal supported" themes or would you have to manually add support into pywal for each new theme?

**Comment by dylanaraps** [comment]
I modified the theme to use special variables exported by `pywal`. Example:

```
gtk-color-scheme = "background: #1C1F20"
gtk-color-scheme = "foreground: #E3E4DF"

gtk-color-scheme = "color0: #1C1F20"
gtk-color-scheme = "color1: #907063"
gtk-color-scheme = "color2: #B78C59"
gtk-color-scheme = "color3: #7F7885"
gtk-color-scheme = "color4: #ADA09B"
gtk-color-scheme = "color5: #C9BEB3"
gtk-color-scheme = "color6: #D5D4CF"
gtk-color-scheme = "color7: #E3E4DF"
gtk-color-scheme = "color8: #767879"
gtk-color-scheme = "color9: #907063"
gtk-color-scheme = "color10: #B78C59"
gtk-color-scheme = "color11: #7F7885"
gtk-color-scheme = "color12: #ADA09B"
gtk-color-scheme = "color13: #C9BEB3"
gtk-color-scheme = "color14: #D5D4CF"
gtk-color-scheme = "color15: #E3E4DF"
```

The only thing that is hard-coded is `pywal` copying the above variable file to the right directory. If any custom themes are made then support must be added inside `pywal`. 

```py
def gtk():
    """Move gtkrc files to the correct location."""
    theme_path = os.path.join(HOME, ".themes", "Flatabulous-wal")
    gtk2_file = os.path.join(CACHE_DIR, "colors-gtk2.rc")

    if os.path.isdir(theme_path):
        shutil.copy(gtk2_file, os.path.join(theme_path, "gtk-2.0"))
```

**Comment by Jab2870** [comment]
@kotajacob If you are successful in porting the arc theme, do you think you could share it?

**Comment by kotajacob** [comment]
@Jab2870 Yea definitely!

**Comment by dylanaraps** [comment]
This is now handled by oomox.

**Comment by Clyybber** [comment]
So it doesn't require python2 anymore?

**Comment by dylanaraps** [comment]
Python2 is required to reload GTK2 themes on the fly.

**Comment by Clyybber** [comment]
Hmm, do you require help with supplying a c file that will be called by pywal to let go of the python2 dependency?
